# Generated by Django 3.1 on 2020-09-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrarEspecialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspec', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='cadastrarMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('CRM', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.PositiveIntegerField()),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.cadastrarespecialidades', verbose_name='Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='agendaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(unique_for_date='pub_date')),
                ('horario', models.DateTimeField(unique=True)),
                ('agdMedico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.cadastrarmedicos', verbose_name='Médico')),
            ],
        ),
    ]
