# Generated by Django 3.1 on 2020-09-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_auto_20200904_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamedica',
            name='horario',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadastrarmedicos',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
