# Generated by Django 3.1 on 2020-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_auto_20200904_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamedica',
            options={},
        ),
        migrations.AlterField(
            model_name='agendamedica',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agendamedica',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
