# Generated by Django 3.1 on 2020-09-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_auto_20200904_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamedica',
            options={'verbose_name_plural': 'Agenda medica'},
        ),
        migrations.AlterModelOptions(
            name='cadastrarmedicos',
            options={'verbose_name': 'Medico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RemoveField(
            model_name='agendamedica',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='cadastrarmedicos',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='cadastrarmedicos',
            name='especialidade',
            field=models.ManyToManyField(blank=True, to='especialidades.cadastrarEspecialidades', verbose_name='Especialidade'),
        ),
    ]
