# Generated by Django 3.1 on 2020-09-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_auto_20200905_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamedica',
            name='horario',
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='dataAgenda',
            field=models.DateField(null=True, verbose_name='Data do agendamento'),
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='horaAgenda',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do agendamento'),
        ),
    ]
