# Generated by Django 3.1 on 2020-09-09 00:50

from django.db import migrations, models
import especialidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0009_auto_20200908_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrarespecialidades',
            old_name='nomeEspec',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='agendamedica',
            name='dataAgenda',
            field=models.DateField(null=True, validators=[especialidades.models.agendaMedica.agdPassada], verbose_name='Data do agendamento'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamedica',
            unique_together={('agdMedico', 'dataAgenda')},
        ),
    ]
