# Generated by Django 3.1 on 2020-09-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0010_auto_20200908_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamedica',
            options={'ordering': ['dia'], 'verbose_name_plural': 'Agenda medica'},
        ),
        migrations.RenameField(
            model_name='agendamedica',
            old_name='dataAgenda',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='agendamedica',
            old_name='horaAgenda',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='agendamedica',
            old_name='agdMedico',
            new_name='medico',
        ),
        migrations.AlterUniqueTogether(
            name='agendamedica',
            unique_together={('medico', 'dia')},
        ),
    ]
