# Generated by Django 3.1 on 2020-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0011_auto_20200909_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamedica',
            name='data_agendamento',
            field=models.DateField(auto_now=True),
        ),
    ]
