# Generated by Django 3.1 on 2020-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0012_agendamedica_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamedica',
            name='data_agendamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
