# Generated by Django 3.1 on 2020-09-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0014_auto_20200910_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendaDisponivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dias disponíveis')),
                ('horarios', models.TimeField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('14:00', '14:00'), ('14:30', '14:30')])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.cadastrarmedicos')),
            ],
        ),
    ]
