# Generated by Django 3.1 on 2020-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0015_agendadisponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='horariosDisponiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agendadisponivel',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agendadisponivel',
            name='horarios',
            field=models.ManyToManyField(to='especialidades.horariosDisponiveis'),
        ),
    ]
