# Generated by Django 3.1 on 2020-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0017_auto_20200910_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadisponivel',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agendadisponivel',
            name='horarios',
            field=models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00')], default='08:00', max_length=5),
        ),
    ]
