# Generated by Django 3.1 on 2020-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0018_auto_20200910_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadisponivel',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agendadisponivel',
            name='horarios',
            field=models.ManyToManyField(null=True, to='especialidades.horariosDisponiveis'),
        ),
    ]
