# Generated by Django 3.1 on 2020-09-10 20:26

from django.db import migrations, models
import especialidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0019_auto_20200910_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendadisponivel',
            options={'ordering': ['dia']},
        ),
        migrations.AlterField(
            model_name='agendadisponivel',
            name='dia',
            field=models.DateField(validators=[especialidades.models.agendaDisponivel.agdPassada], verbose_name='Dias disponíveis'),
        ),
        migrations.AlterUniqueTogether(
            name='agendadisponivel',
            unique_together={('medico', 'dia')},
        ),
    ]
